/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

/**
 *
 * @author pablo
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        rbt_M = new javax.swing.JRadioButton();
        rbt_C = new javax.swing.JRadioButton();
        rbt_U = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txta_01 = new javax.swing.JTextArea();
        btn_Go = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rbt_M.setText("México");
        jPanel1.add(rbt_M, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        rbt_C.setText("Canadá");
        jPanel1.add(rbt_C, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        rbt_U.setText("USA");
        jPanel1.add(rbt_U, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        txta_01.setColumns(20);
        txta_01.setRows(5);
        jScrollPane1.setViewportView(txta_01);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 360, 270));

        btn_Go.setText("Go");
        btn_Go.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_GoActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Go, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 70, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_GoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_GoActionPerformed

        String cadena = "";

        if (rbt_M.isSelected()) {

            cadena = "México \n";

        }
        if (rbt_U.isSelected()) {

            cadena += "USA \n";

        }
        if (rbt_C.isSelected()) {

            cadena += "Canadá \n";

        }

        txta_01.setText(cadena);

        rbt_M.setSelected(false);
        rbt_C.setSelected(false);
        rbt_U.setSelected(false);

    }//GEN-LAST:event_btn_GoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Go;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbt_C;
    private javax.swing.JRadioButton rbt_M;
    private javax.swing.JRadioButton rbt_U;
    private javax.swing.JTextArea txta_01;
    // End of variables declaration//GEN-END:variables
}
